openapi: 3.0.0
info:
  title: Felparkering API
  description: Rest API för att hantera felparkerade fordon
  version: '1.0'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
    variables: {}
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Login user
      description: |-
        ### POST /login

        Loggar in användare med e-post och lösenord.  
        Returnerar en JWT-token [`sub`: User ID, `claim`: User Role] som används för autentisering.
      operationId: Loginuser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@example.com
                password:
                  type: string
                  example: abc123
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                user:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6...
                message: User logged in successfully
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorMissingCredentials'
                  - example:
                      error: Missing credentials
              example:
                error: Missing credentials
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorInvalidCredentials'
                  - example:
                      error: Invalid credentials
              example:
                error: Invalid credentials
        '404':
          description: Not Found
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorNotFound'
                  - example:
                      error: User not found
              example:
                error: User not found
      deprecated: false
      security: []
  /register:
    post:
      tags:
        - Auth
      summary: Register new user
      description: |-
        ### POST /register

        Registrerar en användare (CUSTOMER) med e-post och lösenord.
        Returnerar en JWT-token [`sub`: User ID, `claim`: User Role] som används för autentisering.
      operationId: Registernewuser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@example.com
                password:
                  type: string
                  example: abc123
                confPassword:
                  type: string
                  example: abc123
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                  user: 
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6...
                  message: User registered successfully
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missingCredentials: 
                  summary: Missing credentials
                  value:
                    error: Missing credentials
                passwordMismatch:
                  summary: Password and confirmation does not match
                  value:
                    error: Password and confirmation does not match
        '409':
          description: Conflict
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUserConflict'
                  - example:
                      message: 
                      error: User already exists
              example:
                error: User already exists
      deprecated: false
  /reports:
    post:
      tags:
        - Reports
      summary: Create new report
      description: |-
        ### POST /reports

        Skapar en felparkeringsrapport.

        #### Behörighet:

        - `ADMIN`: Ja
            
        - `ATTENDANT`: Nej (403)
            
        - `CUSTOMER`: Ja
      operationId: Createnewreport
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 101
                street:
                  type: string
                  example: Södra vägen
                houseNumbers:
                  type: string
                  example: "1"
                city:
                  type: string
                  example: Stockholm
                licensePlate:
                  type: string
                  example: ABC123
                category:
                  type: string
                  example: BLOCKERAR_UTFART
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ReportCreatedResponse'
                  - example:
                      message: Report created successfully
                      createdOn: '2025-06-17T14:22:00Z'
              example:
                message: Report created successfully
                createdOn: '2025-06-17T14:22:00Z'
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorMissingCredentials'
                  - example:
                      error: Missing credentials
              example:
                error: Missing credentials
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to create a report
              example:
                error: You do not have permission to create a report
      deprecated: false
      security:
        - bearer: []
    get:
      tags:
        - Reports
      summary: Get all reports
      description: |-
        ### GET /reports

        Hämtar en lista med alla felparkeringsrapporter.

        #### Behörighet:

        Roll:

        - `ADMIN`: Ser alla rapporter
            
        - `ATTENDANT`: Ser endast rapporter för sin egen vaktgrupp
            
        - `CUSTOMER`: Ser endast rapporter som de har skapat
      operationId: Getallreports
      parameters: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
                description: ''
                example:
                  - id: 12
                    address:
                      id: 101
                      street: Södra vägen
                      houseNumbers:
                        - "1"
                      city: Stockholm
                      latitude: 59.33
                      longitude: 18.06
                      distanceFromCity: 120
                    licensePlate: ABC123
                    category: BLOCKERAR_UTFART
                    attendantGroup:
                      id: 1
                      name: Stockholm Södra
                    assignedToId: 7
                    createdOn: '2025-06-17T14:22:00Z'
                    updatedOn: '2025-06-17T14:22:00Z'
                    status: NEW
                  - id: 13
                    address:
                        id: 102
                        street: Norra vägen
                        houseNumbers:
                          - "3"
                        city: Stad
                        latitude: 13.91
                        longitude: 56.52
                        distanceFromCity: 220
                    licensePlate: ABC123
                    category: SAKNAR_TILLSTAND
                    attendantGroup:
                      id: 1
                      name: Stockholm Södra
                    assignedToId: 7
                    createdOn: '2025-06-17T15:17:00Z'
                    updatedOn: '2025-06-17T15:17:00Z'
                    status: NEW   
              example:
                - id: 12
                  address:
                    id: 101
                    street: Södra vägen
                    houseNumbers:
                      - "1"
                    city: Stockholm
                    latitude: 59.33
                    longitude: 18.06
                    distanceFromCity: 120
                  licensePlate: ABC123
                  category: BLOCKERAR_UTFART
                  attendantGroup:
                    id: 1
                    name: Stockholm Södra
                  assignedToId: 7
                  createdOn: '2025-06-17T14:22:00Z'
                  updatedOn: '2025-06-17T14:22:00Z'
                  status: NEW
                - id: 13
                  address:
                      id: 102
                      street: Norra vägen
                      houseNumbers:
                        - "3"
                      city: Stad
                      latitude: 13.91
                      longitude: 56.52
                      distanceFromCity: 220
                  licensePlate: ABC123
                  category: SAKNAR_TILLSTAND
                  attendantGroup:
                    id: 1
                    name: Stockholm Södra
                  assignedToId: 7
                  createdOn: '2025-06-17T15:17:00Z'
                  updatedOn: '2025-06-17T15:17:00Z'
                  status: NEW      
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to get all reports
              example:
                error: You do not have permission to get all reports
      deprecated: false
      security:
        - bearer: []
  /reports/{id}:
    get:
      tags:
        - Reports
      summary: Get a report
      description: |-
        ### GET /reports/{id}

        Hämtar detaljerad information om en specifik felparkeringsrapport.

        #### Behörighet:

        - `ADMIN`: Har tillgång till alla rapporter
            
        - `ATTENDANT`: Har tillgång om rapporten tillhör samma vaktgrupp
            
        - `CUSTOMER`: Har tillgång om rapporten är skapad av användaren
            

        #### Parameter

        - `id` _(Long)_ – rapportens ID
      operationId: Getareport
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Report'
                  - example:
                      id: 12
                      address:
                        id: 101
                        street: Södra vägen
                        houseNumbers:
                          - "1"
                        city: Stad
                        latitude: 59.3293
                        longitude: 18.0686
                        distanceFromCity: 120
                      licensePlate: ABC123
                      category: BLOCKERAR_UTFART
                      attendantGroup:
                        id: 1
                        name: Stockholm Södra
                      assignedToId: 7
                      createdOn: '2025-06-17T14:22:00Z'
                      updatedOn: '2025-06-17T14:22:00Z'
                      status: NEW
              example:
                id: 12
                address:
                  id: 101
                  street: Södra vägen
                  houseNumbers:
                    - "1"
                  city: Stad
                  latitude: 59.3293
                  longitude: 18.0686
                  distanceFromCity: 120
                licensePlate: ABC123
                category: BLOCKERAR_UTFART
                attendantGroup:
                  id: 1
                  name: Stockholm Södra
                assignedToId: 7
                createdOn: '2025-06-17T14:22:00Z'
                updatedOn: '2025-06-17T14:22:00Z'
                status: NEW
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to get a report
              example:
                error: You do not have permission to get a report
        '404':
          description: Not Found
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorNotFound'
                  - example:
                      error: Report not found
              example:
                error: Report not found
      deprecated: false
      security:
        - bearer: []
    put:
      tags:
        - Reports
      summary: Update report status
      description: |-
        ### PUT/reports/{id}

        Uppdaterar informationen för en specifik felanmälan, t.ex. ändrar dess status.

        #### Behörighet:

        - `ADMIN`: kan uppdatera alla fält
            
        - `ATTENDANT`: kan ändra status om rapporten tillhör deras vaktgrupp
            
        - `CUSTOMER`: kan ändra status på sina egna ärenden om de är aktiva till `CANCELLED`
            

        #### Parameter

        - `id` _(Long)_ – rapportens ID
      operationId: Updatereportstatus
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Updated
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportUpdatedResponse'
                example:
                  message: Report updated successfully
                  createdOn: '2025-06-17T14:22:00Z'
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to update a report
              example:
                error: You do not have permission to update a report
      deprecated: false
      security:
        - bearer: []
  /admin/attendant:
    post:
      tags:
        - Admin
      summary: Create Attendant
      description: |-
        ### POST /admin/attendant

        Skapar en parkeringsvakt och tilldelar den en vaktgrupp.

        #### Behörighet:

        - `ADMIN`: Ja
            
        - `ATTENDANT`: Nej (403)
            
        - `CUSTOMER`: Nej (403)
      operationId: CreateAttendant
      parameters: []
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/AttendantCreatedResponse'
                  - example:
                      message: Vakt registrerad
                      email: vakt@example.com
                      attendantGroup:
                        id: 1
                        name: Stockholm Södra
              example:
                message: Vakt registrerad
                email: vakt@example.com
                attendantGroup:
                  id: 1
                  name: Stockholm Södra
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorMissingCredentials'
                  - example:
                      error: Missing credentials
              example:
                error: Missing credentials
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to create an attendant
              example:
                error: You do not have permission to create an attendant
      deprecated: false
      security:
        - bearer: []
  /admin/users:
    get:
      tags:
        - Admin
      summary: Get all users
      description: |-
        ### GET /admin/users

        Hämtar en lista med alla användare.

        #### Behörighet:

        Roll:

        - `ADMIN`: ser alla användare
            
        - `ATTENDANT`: ej tillåten (403)
            
        - `CUSTOMER`: ej tillåten (403)
      operationId: Getallusers
      parameters: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                description: ''
                example:
                  - id: 1
                    email: Stockholm Södra
                    role: CUSTOMER
                  - id: 7
                    email: Stockholm Norra
                    role: ATTENDANT
                    attendantGroup:
                      id: 1
                      name: Stockholm Södra
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to get all users
              example:
                error: You do not have permission to get all users
      deprecated: false
      security:
        - bearer: []
  /admin/users/{id}:
    delete:
      tags:
        - Admin
      summary: Delete user
      description: |-
        ### DELETE /admin/users/{id}

        Tar bort en användare med {id}.

        #### Behörighet:

        - `ADMIN`: Ja
            
        - `ATTENDANT`: ej tillåtet (403)
            
        - `CUSTOMER`: ej tillåtet (403)
            

        #### Parameter

        - `id` _(Long)_ – användarens ID
      operationId: Deleteuser
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DeletedResponse'
                  - example:
                      message: User was successfully deleted
              example:
                message: User was successfully deleted
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to delete a user
              example:
                error: You do not have permission to delete a user
        '404':
          description: Not Found
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorNotFound'
                  - example:
                      error: User not found
              example:
                error: User not found
      deprecated: false
      security:
        - bearer: []
  /admin/attendants:
    get:
      tags:
        - Admin
      summary: Get all Attendant Groups
      description: |-
        ### GET /admin/attendants

        Hämtar en lista med alla vaktgrupper.

        #### Behörighet:

        Roll:

        - `ADMIN`: ser alla vaktgrupper
            
        - `ATTENDANT`: ej tillåten (403)
            
        - `CUSTOMER`: ej tillåten (403)
      operationId: GetallAttendantGroups
      parameters: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendantGroup'
                description: ''
                example:
                  - id: 1
                    name: Stockholm Södra
                  - id: 2
                    name: Stockholm Norra
              example:
                - id: 1
                  name: Stockholm Södra
                - id: 2
                  name: Stockholm Norra
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorUnauthorized'
                  - example:
                      error: Missing or invalid token
              example:
                error: Missing or invalid token
        '403':
          description: Forbidden
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ErrorAccessDenied'
                  - example:
                      error: You do not have permission to get all attendant groups
              example:
                error: You do not have permission to get all attendant groups
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    LoginResponse:
      title: LoginResponse
      required:
        - user
        - message
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserDetailDto'
        message:
          type: string
      example:
        user:
          token: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        message: User logged in successfully
    ErrorResponse:
      title: ErrorResponse
      type: object
      required:
        - error
      properties:
        error:
          type: string
      example:
        error: Bad request
    ErrorMissingCredentials:
      title: ErrorMissingCredentials
      required:
        - error
      type: object
      properties:
        error:
          type: string
      example:
        error: Missing credentials
    ErrorInvalidCredentials:
      title: ErrorInvalidCredentials
      required:
        - error
      type: object
      properties:
        error:
          type: string
      example:
        error: Invalid credentials
    ErrorNotFound:
      title: ErrorNotFound
      required:
        - error
      type: object
      properties:
        error:
          type: string
      example:
        error: User not found
    ErrorUserConflict:
      title: ErrorUserConflict
      required:
        - error
      type: object
      properties:
        error:
          type: string
      example:
        error: User already exists
    RegisterResponse:
      title: RegisterResponse
      required:
        - user
        - message
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserDetailDto'
        message:
          type: string
      example:
        user:
          token: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        message: User registered successfully
    ReportCreatedResponse:
      title: ReportCreatedResponse
      required:
        - message
        - createdOn
      type: object
      properties:
        message:
          type: string
        createdOn:
          type: string
      example:
        message: Report created successfully
        createdOn: '2025-06-17T14:22:00Z'
    ReportUpdatedResponse:
      title: ReportUpdatedResponse
      required:
        - message
        - updatedOn
      type: object
      properties:
        message:
          type: string
        updatedOn:
          type: string
      example:
        message: Report updated successfully
        updatedOn: '2025-06-17T14:22:00Z'
    AttendantGroup:
      title: AttendantGroup
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      example:
        id: 1
        name: Stockholm Södra
    ErrorUnauthorized:
      title: ErrorUnauthorized
      required:
        - error
      type: object
      properties:
        error:
          type: string
      example:
        error: Missing or invalid token
    ErrorAccessDenied:
      title: ErrorAccessDenied
      required:
        - error
      type: object
      properties:
        error:
          type: string
      example:
        error: You do not have permission to create a report
    Address:
      title: Address
      required:
        - id
        - longitude
        - latitude
        - street
        - houseNumbers
        - city
        - distanceFromCity
      type: object
      properties:
        id:
          type: integer
          format: int64
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        street:
          type: string
        houseNumbers:
          type: array
          items:
            type: string
        city:
          type: string
        distanceFromCity:
          type: number
          format: double
      example:
        id: 101
        longitude: 18.06
        latitude: 59.33
        street: Södra vägen
        houseNumbers:
          - "1"
        city: Stockholm
        distanceFromCity: 120
    Report:
      title: Report
      required:
        - id
        - address
        - licensePlate
        - category
        - attendantGroup
        - assignedToId
        - createdOn
        - updatedOn
        - status
      type: object
      properties:
        id:
          type: integer
          format: int64
        address:
          $ref: '#/components/schemas/Address'
        licensePlate:
          type: string
        category:
          type: string
        attendantGroup:
          $ref: '#/components/schemas/AttendantGroup'
        assignedToId:
          type: integer
          format: int64
          nullable: true
          description: ID of the attendant assigned to the report. Null if unassigned.
        createdOn:
          type: string
          format: date-time
        updatedOn:
          type: string
          format: date-time
        status:
          type: string
      example:
        id: 12
        address:
          id: 101
          street: Södra vägen
          houseNumbers:
            - "1"
          city: Stockholm
          latitude: 59.33
          longitude: 18.06
          distanceFromCity: 120
        licensePlate: ABC123
        category: BLOCKERAR_UTFART
        attendantGroup:
          id: 1
          name: Stockholm Södra
        assignedToId: 7
        createdOn: '2025-06-17T14:22:00Z'
        updatedOn: '2025-06-17T14:22:00Z'
        status: NEW
    AttendantCreatedResponse:
      title: AttendantCreatedResponse
      required:
        - message
        - email
        - attendantGroup
      type: object
      properties:
        message:
          type: string
        email:
          type: string
        attendantGroup:
          $ref: '#/components/schemas/AttendantGroup'
      example:
        message: Vakt registrerad
        email: vakt@example.com
        attendantGroup:
          id: 1
          name: Stockholm Södra
    User:
      title: User
      required:
        - id
        - email
        - role
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
        role:
          type: string
        attendantGroup:
          type: object
          nullable: true
          allOf:
            - $ref: '#/components/schemas/AttendantGroup'
            - example:
                id: 1
                name: Stockholm Södra
      example:
          id: 7
          email: Stockholm Norra
          role: ATTENDANT
          attendantGroup:
            id: 1
            name: Stockholm Södra
    UserDetailDto:
      title: UserDetailDto
      required:
        - token
      type: object
      properties:
        token:
          type: string
          description: JWT token där `sub` claim innehåller användarens id.
      example:
          token: eyJhbGciOiJIUzI1NiIsInR5cCI6...
    DeletedResponse:
      title: DeletedResponse
      required:
        - message
      type: object
      properties:
        message:
          type: string
      example:
        message: User was successfully deleted
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
    description: Authentication endpoints
  - name: Reports
    description: Report management endpoints
  - name: Admin
    description: Admin management endpoints